### ISSUE TITLE
Support for vim8

### ISSUE THREAD

**Issue by kepbod** [roxma/python-support.nvim#4]
Could this plugin support for vim8? If not, do you have any plan to support for vim8?

**Comment by roxma** [comment]
Doesn't support vim8 currently. This plugin was born before NCM and vim-hug-neovim-rpc, I've never thought about this before. Maybe in the future, when I have some free time.

But vim8 doesn't recognize `g:python3_host_prog` or `g:python_host_prog` like neovim does. So It can't setup dependency for vim's builtin `:python` command like it does for neovim. It seems vim choose the python at compile time.

By the way, you could always setup python dependency manually.

**Comment by kepbod** [comment]
Sure. Thanks for your answer.
