### ISSUE TITLE
E118: Too many arguments for function: <SNR>31_py2/3requirements errors

### ISSUE THREAD

**Issue by partounian** [roxma/python-support.nvim#6]
On Ubuntu 14.04 server I am getting these errors on vim startup. 
E118: Too many arguments for function: <SNR>31_py2requirements
E118: Too many arguments for function: <SNR>31_py3requirements
I have run the :PythonSupportInit functions without issues, but with the plugin enabled I get these errors. 

On my Mac, I have the same vim settings but no errors.

**Comment by roxma** [comment]
Thanks for the feedback.

Let me know if the problem still exists.
