### ISSUE TITLE
how this works if I have Pyenv ?

### ISSUE THREAD

**Issue by ysolis** [roxma/python-support.nvim#9]
I have Pyenv (https://github.com/pyenv/pyenv) to manage all my Python version and virtualenv/venv for several projects.

Can this plugin detect this and build the virtualenvs needed inside pyenv ? Actually I build to pyenv-virtualenv, py2_neovim and py3_neovim, with neovim eggs installed, can be this be autoamted with these tool?

**Comment by roxma** [comment]
I'm not sure about what you want. Can you elaborate?

**Comment by ysolis** [comment]
this plugin build virtualenvs/venvs for Python 2/3 for neovim usage (installing neovim egg and other ones that you indicate).

with PyEnv you can create virtualenvs for Python 2/3 with `pyenv virtualenv` command you need to install previously Python2/3 (pyenv provides the virtualenv requirements) 

I like to know if the plugin can work with PyEnv (building the venvs behind scenes and installing neovim on this). If appear to be much work, then no problem really.

**Comment by roxma** [comment]
This plugin uses the `python2` and `python3` in your `$PATH` to create the virtualenv. It doesn't use `pyenv`

**Comment by ysolis** [comment]
well, then, don't fix needed.
